- .circleci/config.yml
- README.md
[Trello ticket](https://trello.com/c/m7o67xlr)
No continuous integration service is integrated  
1. Create pull request
Ensure you've got status checks for lint and test commands
Ensure repository's README has a nice Circle CI badge :)
Integrate with Circle CI
> Feat: integrate Circle CI

- src/components/app/App.css
- src/components/app/App.jsx
- src/components/button/Button.css
- src/components/button/Button.jsx
- src/components/button/Button.stories.jsx
- src/components/button/Button.test.jsx
- src/components/button/index.js
- src/components/nav/Nav.css
- src/components/nav/Nav.jsx
- src/components/product/Product.jsx
- src/components/product/product-type-button/ProductTypeButton.css
- src/components/product/product-type-button/ProductTypeButton.jsx
- src/components/product/product-type-button/ProductTypeButton.stories.jsx
- src/components/product/product-type-button/index.js
- src/components/utils/withClassName/index.js
- src/components/utils/withClassName/withClassName.jsx
- src/components/utils/withClassName/withClassName.test.jsx
[Trello ticket](https://trello.com/c/TzHods5O)
Duplication of button elements
View code, verify that UI didn't change at all
Extract Button and ProductTypeButton components. Create util function withClassName.
> Refactor: extract button component

- src/components/app/App.css
- src/components/app/App.jsx
- src/components/labelled-input/LabelledInput.css
- src/components/product/Product.css
- src/components/product/Product.jsx
- src/components/product/Product.stories.jsx
- src/components/product/Product.test.jsx
[Trello ticket](https://trello.com/c/xV8hdHoM)
very static product types. No event handler for select product type
Run tests
View stories of Product
Make sure, that onSelectProductType event is fired correctly
Make sure, that it's possible to add new productTypes simply in the array in App.jsx
Add new props to Product, add stories and tests
> Feat: make product types more dynamic

- package.json
- yarn.lock
[Trello ticket](https://trello.com/c/tC2Conk2)
Outdated react-scripts version
Verify that everything is workings: linter, tests, UI
Update dependencies, disallow warnings
> Chore: update react-scripts

- .circleci/config.yml
- .eslintrc.json
- .prettierignore
- package.json
[Trello ticket](https://trello.com/c/x2zlpY0l)
files in .storybook are formatted incorrect according to our style guide.
Ensure, that eslint runs on storybook config files.
Prettify storybook and Circle CI config files, run eslint on them.
> Chore: run eslint on storybook config

- package.json
- src/components/app/App.jsx
- src/components/nav/Nav.jsx
- src/components/pages/add-order-page/AddOrderPage.jsx
- src/components/pages/add-order-page/AddOrderPage.test.jsx
- src/components/pages/add-order-page/index.js
[Trello ticket](https://trello.com/c/xJILFUwu/44-add-react-router)
Soon we will add second page. So we need client side routing to handle pages.
Try to add new pages, verify everything works
Add @reach/router
> Feat: add router

- src/components/app/App.jsx
- src/components/nav/Nav.jsx
- src/components/pages/search-page/SearchPage.jsx
- src/components/pages/search-page/index.js
[Trello ticket](https://trello.com/c/bOmR6dQ8/46-create-search-page)
Need to create initial search page
Click on Search page in Nav, verify Search page is opened.
Create search page
> Feat: create empty search page

- PULL_REQUEST_TEMPLATE.md
[Trello ticket](https://trello.com/c/3NEL0mlI/58-simplify-pull-request-template)
deleted some requests from PULL_REQUEST_TEMPLATE.md file
deleted one request and checkboks
> Change content PULL_REQUEST_TEMPLATE.md

- .circleci/config.yml
- commitlint.config.js
- package.json
- yarn.lock
[Trello ticket](https://trello.com/c/d51Y0edg/55-add-commitlint)
Ensure on CI, that commit messages follow our convention
Read about [commitlint](https://github.com/conventional-changelog/commitlint/), verify that new config works on project and Circle CI
Add and configure commitlint. Run it on CI
> chore: integrate commitlint

- src/components/pages/search-page/SearchPage.css
- src/components/pages/search-page/SearchPage.jsx
[Trello ticket](https://trello.com/c/tqRJR3KH/54-add-search-inputs-to-search-page)
Create UI form submission for search-page
It need to see
I made form tag for submission data order. It have inside 5 inputs tag and button for submittion. And I added styles with help display grid.
> Create form UI for search page

- src/components/customer-data/index.js
- src/components/order-data/OrderData.css
- src/components/order-data/OrderData.jsx
- src/components/order-data/index.js
- src/components/pages/add-order-page/AddOrderPage.jsx
[Trello ticket](https://trello.com/c/jWMtidAS/52-rename-customerdata-to-orderdata)
Changed name CustomerData to OrderData
have been rename:
- folder
- js file
- component name
- css file
- css class
Also all usages of this component should be updated to reflect changes in path
> Rename CustomerData to OrderData

- src/components/pages/add-order-page/AddOrderPage.jsx
- src/components/product/Product.jsx
[Trello ticket](https://trello.com/c/JCgR2WIh/62-add-product-parameters-to-formik)
Product parameters are not saved anywhere.
Save them in Formik state
> chore: save product parameters in Formik

- src/components/labelled-date-input/LabelledDateInput.jsx
- src/components/labelled-field/LabelledField.jsx
- src/components/labelled-input/LabelledInput.jsx
- src/components/order-data/OrderData.jsx
- src/components/pages/add-order-page/AddOrderPage.jsx
- src/components/product/Product.css
[Trello ticket](https://trello.com/c/B9l0rhJa/63-add-orderdata-and-orderid-to-formik)
OrderData and order id are not in Formik state.
Add them. Change few components to support Formik
> Chore: add order id and order data to formik

- src/components/app/App.jsx
- src/components/pages/order-page/OrderPage.jsx
[Trello ticket](https://trello.com/c/DnajQE5d/67-create-order-client-page)
No view/edit order page 
Add "view/edit order page"
> chore: add empty order page

- .circleci/config.yml
- package.json
- src/components/order-table/OrderTable.css
- src/components/order-table/OrderTable.jsx
- src/components/order-table/OrderTable.stories.jsx
- src/components/pages/search-page/SearchPage.css
- src/components/pages/search-page/SearchPage.jsx
- yarn.lock
[Trello ticket](https://trello.com/c/O4RDJ2T2/64-add-table-for-results-on-search-page)
add table for results on search page
add table and fill it with a fake array
> Add table for results on search page

- src/components/pages/search-page/SearchPage.jsx
[Trello ticket](https://trello.com/c/OWqP7l89/71-add-formik-to-search-page)
Add Formik to Search page
add wrap Formik around Form, create formikState.
> Add Formik to Search page

- packages/backend/get-orders-count_handler.js
- packages/backend/serverless.yml
[Trello ticket](https://trello.com/c/4Ji6RFZP/78-create-get-orders-count-api)
Create "get-orders-count" api
Implement lambda function witch return orders count
> Create "get-orders-count" api

- README.md
- package.json
- packages/backend/config.js
- packages/backend/middlewares.js
- packages/backend/package.json
- packages/backend/serverless.yml
- packages/backend/utils.js
- packages/frontend/.env.example
- packages/frontend/.env.test
- packages/frontend/.gitignore
- packages/frontend/package.json
- packages/frontend/src/components/order-data/OrderData.jsx
- packages/frontend/src/components/pages/add-order-page/AddOrderPage.css
- packages/frontend/src/components/pages/add-order-page/AddOrderPage.jsx
- packages/frontend/src/components/pages/add-order-page/addOrderPage_service.js
- packages/frontend/src/components/product/Product.jsx
- packages/frontend/src/components/utils/Loader/Loader.css
- packages/frontend/src/components/utils/Loader/Loader.jsx
- packages/frontend/src/configureStore.js
- packages/frontend/src/index.jsx
- packages/frontend/src/utils.js
- yarn.lock
[Trello ticket for integrating create order api](https://trello.com/c/GcnMS3Ym/80-integrate-create-order-api-into-frontend)
[Trello ticket for allowing cors](https://trello.com/c/XIKW2sqD/82-allow-cors)
Need to send orders to backend to save them
Integrate "create order" api into frontend
> feat: integrate create order api & allow cors

- packages/frontend/src/components/pages/add-order-page/AddOrderPage.jsx
- packages/frontend/src/components/pages/add-order-page/addOrderPage_service.js
[Trello ticket](https://trello.com/c/NC8R7vPI/81-integrate-get-orders-count-api-into-frontend)
Use "get-orders-count" api in frontend
Make request to "get-orders-count"
> Integrate get orders count api into frontend

- packages/backend/get-order_handler.js
- packages/backend/serverless.yml
- packages/frontend/src/components/pages/search-page/SearchPage.jsx
- packages/frontend/src/components/pages/search-page/searchPage_service.js
[Trello ticket](https://trello.com/c/DatRI8W4/84-create-get-order-api)
get order by id
Made handler on backend and function with request on frontend
> Create get order api

- packages/backend/src/orders-logic.js
- packages/backend/src/orders-logic.test.js
- packages/frontend/src/components/order-table/OrderTable.css
- packages/frontend/src/components/order-table/OrderTable.jsx
- packages/frontend/src/components/pages/search-page/SearchPage.jsx
- packages/frontend/src/components/pages/search-page/searchPage_service.js
[Trello ticket](https://trello.com/c/RdK9LjF2/86-integrate-search-api-into-frontend)
Integrate search api into frontend
Create a function, which return list orders by parameters and rendering it
> Integrate search api into frontend

- packages/frontend/package.json
- packages/frontend/src/components/LabelledPhoneInput/LabelledPhoneInput.css
- packages/frontend/src/components/LabelledPhoneInput/LabelledPhoneInput.jsx
- packages/frontend/src/components/order-data/OrderData.css
- packages/frontend/src/components/order-data/OrderData.jsx
- packages/frontend/src/components/pages/search-page/SearchPage.css
- packages/frontend/src/components/pages/search-page/SearchPage.jsx
- yarn.lock
[Trello ticket](https://trello.com/c/b2dHieKf/25-phone-placeholders)
Create phone placeholders
Create phone placeholders use 'react-phone-input-2'
> Create phone placeholders
